repos:
    - repo: local
      hooks:
          - id: yarn format
            name: yarn format
            language: system
            pass_filenames: false
            entry: sh -c "cd client && yarn format && git add -A"
            files: ^client/
