repos:
  - repo: local
    hooks:
      - id: yarn-format
        name: Run yarn format
        language: system
        pass_filenames: false
        entry: sh -c "cd client && yarn format && git add -A"
        files: ^client/

      - id: gofmt
        name: Run gofmt
        language: system
        pass_filenames: false
        entry: sh -c "cd api && gofmt -s -w . && git add -A"
        types: [go]

      - id: go-mod-tidy
        name: Tidy go.mod
        language: system
        pass_filenames: false
        entry: sh -c "cd api && go mod tidy"
        files: go\.(mod|sum)$

      - id: sqlc-generate
        name: Generate go models from sql
        entry: sh -c "cd api && sqlc generate"
        language: system
        pass_filenames: false
        files: \.sql$
