repos:
  - repo: local
    hooks:
      - id: yarn-format
        name: Run yarn format
        language: system
        pass_filenames: false
        entry: sh -ce "cd client && yarn format"
        files: ^client/

      - id: yarn-typecheck
        name: Run yarn type-check
        language: system
        pass_filenames: false
        entry: sh -ce "cd client && yarn type-check"
        files: ^client/

      - id: gofmt
        name: Run gofmt
        language: system
        pass_filenames: false
        entry: sh -ce "cd api && gofmt -s -w ."
        types: [go]

      - id: go-mod-tidy
        name: Tidy go.mod
        language: system
        pass_filenames: false
        entry: sh -ce "cd api && go mod tidy"
        files: go\.(mod|sum)$

      - id: sqlc-generate
        name: Generate go models from sql
        entry: sh -ce "cd api && go tool sqlc generate"
        language: system
        pass_filenames: false
        files: \.sql$
