services:
  api:
    build:
      context: api
    command: gow run cmd/main.go
    #command: dlv debug --headless --listen=:12345 --continue --accept-multiclient cmd/main.go
    # security_opt: # IMPORTANT: only use when debugging
    #   - seccomp:unconfined
    ports:
      - "8000:8000"
      - "12345:12345"
    environment:
      - "VALKEY_ADDR=db:6379"
    volumes:
      - ./api:/app

  caddy:
    build:
      context: .
      dockerfile: caddy/Dockerfile
    environment:
      - "CADDY_HOST=:8080"
    ports:
      - "8080:8080"
    volumes:
      - ./client/dist:/srv:ro   # Live client updates
      - caddy-data:/data

  client:
    build:
      context: client
    command: yarn build --watch --sourcemap
    environment:
      - NODE_ENV=development
      - VITE_DEV=1
      - VITE_COMMIT_SHA
      - VITE_LAST_COMMIT_DATE
    volumes:
      - ./client:/app

  db:
    build:
      context: valkey
    volumes:
      - dbdata:/data

volumes:
  caddy-data:
  dbdata:
