services:
  api:
    image: ghcr.io/kangaroux/booruview-api:latest
    restart: unless-stopped
    environment:
      - "VALKEY_ADDR=db:6379"

  caddy:
    image: ghcr.io/kangaroux/booruview-caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - "CADDY_HOST=booruview.com"

  db:
    image: ghcr.io/kangaroux/booruview-valkey:latest
    restart: unless-stopped
    volumes:
      - valkey-data:/data

volumes:
  valkey-data:
