services:
  api:
    build:
      context: api
    command: gow run .
    environment:
      - "VALKEY_ADDR=db:6379"
    volumes:
      - ./api:/app

  caddy:
    build:
      context: .
      dockerfile: caddy/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./client/dist:/srv:ro   # Live client updates

  client:
    build:
      context: client
    command: yarn build --watch --sourcemap
    volumes:
      - ./client:/app

  db:
    image: valkey/valkey:8.1-alpine
    command: valkey-server --save 60 1 --loglevel warning
    volumes:
      - dbdata:/data

volumes:
  dbdata:
