services:
  api:
    build:
      context: api
    command: gow run .
    environment:
      - DBURL=postgres://postgres:password@db/viewer
    volumes:
      - ./api:/app

  caddy:
    build:
      context: .
      dockerfile: caddy/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./client/dist:/srv:ro   # Live client updates

  client:
    build:
      context: client
    command: yarn build --watch --sourcemap
    volumes:
      - ./client:/app

  db:
    image: postgres:17.4-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=viewer
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
