services:
  api:
    image: ghcr.io/jessienyan/booruview-api:latest
    restart: unless-stopped
    environment:
      - "VALKEY_ADDR=db:6379"
    env_file:
      - ".env"
    # Requires loki plugin:
    # docker plugin install grafana/loki-docker-driver:3.3.2-amd64 --alias loki --grant-all-permissions
    logging: &logging
      driver: loki
      options:
        loki-retries: 5
        loki-batch-size: 400
        loki-url: http://localhost:3100/loki/api/v1/push

  caddy:
    image: ghcr.io/jessienyan/booruview-caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - "CADDY_HOST=booruview.com, www.booruview.com"
    logging: *logging
    volumes:
      - caddy-data:/data
      - ./caddy.log:/var/log/caddy.log

  db:
    image: ghcr.io/jessienyan/booruview-valkey:latest
    restart: unless-stopped
    volumes:
      - valkey-data:/data
    logging: *logging

  grafana:
    image: grafana/grafana:11.6.0
    restart: unless-stopped
    environment:
      - "GF_SERVER_ROOT_URL=https://grafana.localhost/"
    volumes:
      - grafana-data:/var/lib/grafana

  loki:
    image: grafana/loki:3.5.0
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki

networks:
  default:
    # Fixes client IP not being passed to container when connecting via ipv6
    # https://github.com/moby/moby/issues/44408
    enable_ipv6: true

volumes:
  caddy-data:
  grafana-data:
  loki-data:
  valkey-data:
