services:
  api:
    build:
      context: api
    command: gow run .
    volumes:
      - ./api:/app

  caddy:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./client/dist:/srv:ro   # Live client updates

  client:
    build:
      context: client
    command: yarn build --watch --sourcemap
    volumes:
      - ./client:/app
