# Requires loki plugin:
# docker plugin install grafana/loki-docker-driver:3.3.2-amd64 --alias loki --grant-all-permissions


services:
  api:
    build:
      context: api
    command: gow run cmd/main.go
    #command: dlv debug --headless --listen=:12345 --continue --accept-multiclient cmd/main.go
    # security_opt: # IMPORTANT: only use when debugging
    #   - seccomp:unconfined
    ports:
      - "8000:8000"
      - "12345:12345"
    environment:
      - "VALKEY_ADDR=db:6379"
    volumes:
      - ./api:/app
    logging: &logging
      driver: loki
      options:
        loki-retries: 5
        loki-batch-size: 100
        loki-url: http://localhost:3100/loki/api/v1/push

  caddy:
    build:
      context: .
      dockerfile: caddy/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./client/dist:/srv:ro   # Live client updates
      - caddy-data:/data
    logging: *logging

  client:
    build:
      context: client
    command: yarn build --watch --sourcemap
    environment:
      - NODE_ENV=development
      - VITE_DEV=1
    volumes:
      - ./client:/app

  db:
    build:
      context: valkey
    volumes:
      - dbdata:/data
    logging: *logging

  grafana:
    image: grafana/grafana:11.6.0
    environment:
      - "GF_SERVER_ROOT_URL=https://grafana.localhost/"
    volumes:
      - grafana-data:/var/lib/grafana

  loki:
    image: grafana/loki:3.5.0
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki

volumes:
  caddy-data:
  dbdata:
  grafana-data:
  loki-data:
