services:
  api:
    image: codeberg.org/jessienyan/booruview/api:latest
    restart: unless-stopped
    environment:
      - "VALKEY_ADDR=db:6379"
    env_file:
      - ".env"
    # Requires loki plugin:
    # docker plugin install grafana/loki-docker-driver:3.3.2-amd64 --alias loki --grant-all-permissions
    logging: &logging
      driver: loki
      options:
        loki-retries: 5
        loki-batch-size: 400
        loki-url: http://localhost:3100/loki/api/v1/push

  caddy:
    image: codeberg.org/jessienyan/booruview/caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - "CADDY_HOST=booruview.com, www.booruview.com"
    logging: *logging
    volumes:
      - caddy-data:/data
      - ./logs/:/var/log/caddy/

  db:
    image: codeberg.org/jessienyan/booruview/valkey:latest
    restart: unless-stopped
    volumes:
      - valkey-data:/data
    logging: *logging

  grafana:
    image: grafana/grafana:11.6.0
    restart: unless-stopped
    environment:
      - "GF_SERVER_ROOT_URL=https://grafana.localhost/"
    volumes:
      - grafana-data:/var/lib/grafana

  loki:
    image: grafana/loki:3.5.0
    restart: unless-stopped
    configs:
      - source: loki_config
        target: /etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki

configs:
  loki_config:
    content: |
      ###### Custom options ######
      compactor:
        retention_enabled: true
        retention_delete_delay: 2h
        delete_request_store: filesystem

      limits_config:
        max_query_series: 100000
        retention_period: 365d

      ###### Below are defaults from container /etc/loki/local-config.yaml ######
      auth_enabled: false
      server:
        http_listen_port: 3100
      common:
        instance_addr: 127.0.0.1
        path_prefix: /loki
        storage:
          filesystem:
            chunks_directory: /loki/chunks
            rules_directory: /loki/rules
        replication_factor: 1
        ring:
          kvstore:
            store: inmemory
      schema_config:
        configs:
          - from: 2020-10-24
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: index_
              period: 24h
      ruler:
        alertmanager_url: http://localhost:9093

networks:
  default:
    # Fixes client IP not being passed to container when connecting via ipv6
    # https://github.com/moby/moby/issues/44408
    enable_ipv6: true

volumes:
  caddy-data:
  grafana-data:
  loki-data:
  valkey-data:
