// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package models

import (
	"database/sql"
)

type UserData struct {
	UserID    int64        `db:"user_id"`
	UpdatedAt sql.NullTime `db:"updated_at"`
	Data      string       `db:"data"`
}

type Users struct {
	ID           int64        `db:"id"`
	CreatedAt    sql.NullTime `db:"created_at"`
	LastLogin    sql.NullTime `db:"last_login"`
	Username     string       `db:"username"`
	Password     string       `db:"password"`
	PasswordSalt string       `db:"password_salt"`
}
