// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package models

import (
	"database/sql"
	"time"
)

type UserData struct {
	UserID    int64        `db:"user_id"`
	UpdatedAt sql.NullTime `db:"updated_at"`
	Data      string       `db:"data"`
}

type Users struct {
	ID                int64        `db:"id"`
	CreatedAt         time.Time    `db:"created_at"`
	LastLogin         sql.NullTime `db:"last_login"`
	Username          string       `db:"username"`
	Password          []byte       `db:"password"`
	PasswordSalt      []byte       `db:"password_salt"`
	PasswordChangedAt sql.NullTime `db:"password_changed_at"`
}
