// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package models

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users
(username, password, password_salt)
VALUES (?, ?, ?)
RETURNING id, created_at, last_login, username, password, password_salt
`

type CreateUserParams struct {
	Username     string `db:"username"`
	Password     string `db:"password"`
	PasswordSalt string `db:"password_salt"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Users, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Password, arg.PasswordSalt)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.LastLogin,
		&i.Username,
		&i.Password,
		&i.PasswordSalt,
	)
	return i, err
}

const createUserData = `-- name: CreateUserData :one
INSERT INTO user_data
(user_id, data)
VALUES (?, ?)
RETURNING user_id, updated_at, data
`

type CreateUserDataParams struct {
	UserID int64  `db:"user_id"`
	Data   string `db:"data"`
}

func (q *Queries) CreateUserData(ctx context.Context, arg CreateUserDataParams) (UserData, error) {
	row := q.db.QueryRowContext(ctx, createUserData, arg.UserID, arg.Data)
	var i UserData
	err := row.Scan(&i.UserID, &i.UpdatedAt, &i.Data)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, created_at, last_login, username, password, password_salt FROM users WHERE LOWER(username) = LOWER(?1)
`

func (q *Queries) GetUser(ctx context.Context, username string) (Users, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.LastLogin,
		&i.Username,
		&i.Password,
		&i.PasswordSalt,
	)
	return i, err
}

const getUserData = `-- name: GetUserData :one
SELECT user_id, updated_at, data FROM user_data
WHERE user_id = ?
`

func (q *Queries) GetUserData(ctx context.Context, userID int64) (UserData, error) {
	row := q.db.QueryRowContext(ctx, getUserData, userID)
	var i UserData
	err := row.Scan(&i.UserID, &i.UpdatedAt, &i.Data)
	return i, err
}

const updateUserData = `-- name: UpdateUserData :exec
UPDATE user_data
SET data = ?, updated_at = CURRENT_TIMESTAMP
WHERE user_id = ?
`

type UpdateUserDataParams struct {
	Data   string `db:"data"`
	UserID int64  `db:"user_id"`
}

func (q *Queries) UpdateUserData(ctx context.Context, arg UpdateUserDataParams) error {
	_, err := q.db.ExecContext(ctx, updateUserData, arg.Data, arg.UserID)
	return err
}
