when:
  - event: [pull_request, manual]

steps:
  - name: pre-commit
    image: python:3.14-alpine
    commands: |
      apk update && apk add git
      # Required since we are running as root
      git config --global --add safe.directory '*'
      pip install pre-commit
      pre-commit run -a

  - name: test api
    image: golang:1.25-alpine
    environment:
      SECRET_KEY: test
      VALKEY_ADDR: valkey:6379
    commands: |
      cd api
      export DATABASE_PATH=$(pwd)/database/test.db
      go mod download
      go run ./cmd/goose up
      go test ./...

services:
  - name: valkey
    image: valkey/valkey:8.1-alpine
