FROM golang:1.24-alpine AS build

WORKDIR /app

RUN apk update && apk add ca-certificates && update-ca-certificates

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o /dist/server ./cmd/main.go

FROM scratch

COPY --from=build /dist/server .
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
ENTRYPOINT ["/server"]
